global:
  domain: mukta-uat.digit.org
  tracing-enabled: true
  setup: fullsetup

cluster-configs:
  namespaces:
    create: true
    values:
      [
        backbone,
        cert-manager,
        es-cluster,
        kafka-cluster,
        logging,
        monitoring,
        playground,
        zookeeper-cluster,
        ifix
      ]

  root-ingress:
    cert-issuer: letsencrypt-prod

  secrets:
    db:
      namespace: [ ifix ]
      name: db
    program-service:
      namespace: [ ifix ]
      name: program-service
    elasticsearch:
      namespace: [ ifix ]
      name: elasticsearch-credential

  configmaps:
    egov-config:
      namespace: [ ifix, monitoring ]
      data:
        db-host: "mukta-uat-db.ctm6jbmr5mnj.ap-south-1.rds.amazonaws.com"
        db-name: "mukta_uat_db"
        db-url: "jdbc:postgresql://mukta-uat-db.ctm6jbmr5mnj.ap-south-1.rds.amazonaws.com:5432/mukta_uat_db"
        ifix-db-url: "jdbc:postgresql://mukta-uat-db.ctm6jbmr5mnj.ap-south-1.rds.amazonaws.com:5432/mukta_uat_db?currentSchema=ifix"
        domain: "https://mukta-uat.digit.org"
        egov-services-fqdn-name: "https://mukta-uat.digit.org/"
        egov-state-level-tenant-id: "od"
        es-host: "elasticsearch-data-v8.es-upgrade"
        es-indexer-host: "https://elasticsearch-data-v8.es-upgrade:9200/"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/uat"
        kafka-brokers: "kafka-kraft-controller-headless.kafka-kraft:9092"
        kafka-infra-brokers: "kafka-v2.kafka-cluster:9092"
        logging-level-jdbc: "debug"
        mobile-validation-workaround: "true"
        s3-assets-bucket: "(mukta-uat-bucket-s3)"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-threads: "10"
        server-tomcat-max-connections: "500"
        sms-enabled: "true"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "2"
        spring-jpa-show-sql: "true"
        tracer-errors-provideexceptionindetails: "true"
        timezone: "Asia/Kolkata"
        es-infra-host: elasticsearch-data-v8.es-upgrade
        db-ssl: "false"
        state-level-tenant-id: "od"
        sms-isAdditonalFieldRequired: true
        parent-level-tenant-id: "od"
        java_enable_debug: true

    egov-service-host:
      namespace: [ ifix, monitoring ]
      data:
        egov-mdms-service: "http://egov-mdms-service.egov:8080/"
        egov-enc-service: "http://egov-enc-service.egov:8080/"
        egov-user: "http://egov-user.egov:8080/"
        egov-location: "http://egov-location.egov:8080/"
        egov-accesscontrol: "http://egov-accesscontrol.egov:8080/"
        egov-localization: "http://egov-localization.egov:8080/"
        egov-filestore: "http://egov-filestore.egov:8080/"
        egov-idgen: "http://egov-idgen.egov:8080/"
        egov-workflow-v2: "http://egov-workflow-v2.egov:8080/"

        attendance-service: "http://attendance.works:8080/"
        contract-service: "http://contracts.works:8080/"
        muster-roll-service: "http://muster-roll.works:8080/"
        project-management-system: "http://project.works:8080/"
        estimate-service: "http://estimates.works:8080/"
        organisation: "http://organisation.works:8080/"
        bankaccounts: "http://bankaccounts.works:8080/"
        expense-calculator: "http://expense-calculator.works:8080/"
        expense: "http://expense.works:8080/"
        works-management-service: "http://works-management-service.works:8080/"
        individual: "http://individual.works:8080/"
        works-pdf: "http://works-pdf.works:8080/"
        ifms-jit: "https://uat.odishatreasury.gov.in"
        #ifms-jit: "https://www.odishatreasury.gov.in"
        ifms-adapter: "http://ifms-adapter.works:8080/"
        sms-adapter: "http://sms-adapter.works:8080/"

        audit-service: "http://audit-service.egov:8080/"
        dashboard-analytics: http://dashboard-analytics.egov:8080/
        dashboard-ingest: http://dashboard-ingest.egov:8080/
        data-sync-employee: "http://data-sync-employee:8080/"
        egov-common-masters: "http://egov-common-masters:8080/"
        egov-user-egov: "http://egov-user.egov:8080/"
        egov-otp: "http://egov-otp:8080/"
        minio-url: "http://minio.backbone:9000/"
        egov-common-workflows: "http://egov-common-workflows:8080/"
        egov-workflow: "http://egov-workflow:8080/"
        egov-searcher: "http://egov-searcher.egov:8080/"
        egov-indexer: "http://egov-indexer.egov:8080/"
        egov-hrms: "http://egov-hrms.egov:8080/"
        location: "http://location:8080/"
        pdf-service: "http://pdf-service.egov:8080/"
        user-otp: "http://user-otp:8080/"
        zuul: "http://zuul:8080/"
        egov-url-shortening: "http://egov-url-shortening.egov:8080/"
        inbox: "http://inbox.egov:8080/"
        measurement: "http://measurement-service.works:8080/"
        es-client: https://elasticsearch-data-v8.es-upgrade:9200
        measurement-service: "http://measurement-service.works:8080/"
        measurement-registry: "http://measurement-registry.works:8080/"
        egov-mdms-service-v2: "http://mdms-v2.egov:8080/"
        bulk-upload: "http://bulk-upload.egov:8080/"
        mukta-services: "http://mukta-services.works:8080/"

        digit-exchange: "http://digit-exchange.ifix:8080/"
        program-service: "http://program-service.ifix:8080/"
        ifix-adapter: "http://ifix-adapter.works:8080/"

digit-exchange:
  tracing-enabled: true
  java-enable-debug: true
  app-enable-events-log: true
  app-auth-sign-validation: true
  app-auth-private-key: "-----BEGIN PRIVATE KEY-----MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDrD9z2aCCj1FPsp0c2NbijCcXWFXBu6G+VBHAZLXZjW7uf72xGNgQAgigvJZkz7wqj+B8NIv9vrAAJEnPjUXsATBAgf3GIkKJY+lflT0Cz0TVO8nfzKSXWYKFhyzgA8+185vvFllediuQUCSBnaVy+bYHlup4dZOLuqx/l2NW+kqVoQXDpwigdfAD6gpFvytSrhS10Dcep79Z9n5ajMHRVy83B+YnF5rQWElJIcAdaqFdwE/4xig0r7eueGNvCzEK23R9TvFITPO7HVzbpQ+l4jBM1YiYS5XlgjyHOzE+BW11yyhGp51Jiu0d4ILn6/owHWrvCXDqJK9L096XNm+bHAgMBAAECggEABIDLy16oTWsqZmy39QZncJwl0Zmci0tho9mvahQQYgvmVsSH7vpm7jmQGoMeYbvRGN4Ofjpu6U1CvOnBFZhAgntyjaTTYHng2lKFb4uqoic+XbJQcPSXWHmGbfCuNHp30L4+EYV1TTvVbbrVB5YhpDZF2EhQciC2JjtaA5W5VorAQNt6vcNZ2+CotRRdxwN9ksQfAsVRM17SzeZYyB8ZhObYS8sEndliuMmzdKaIHoAqQsyExE41fY3MuV+G7vOLzzk5mz6hoAoY22u3owwdoJZvRXfGh3yFY7syLdO1ejEuctnqsH5aPlePNq2ZEkrf4Q/aYNzt3IXERrfi6l5ZCQKBgQD6Ok0icgSdBRyqSRjXkzI9RVQ1vXc2kwYqOjwMQ0HDVRzj7SXuG/xr7wAqoYHgdO52lA8pneJ2Rsz+GCJv2t6oZocsaYlAepD1jEoutqhOgsbCqu8n8M2RiOwhhY6DhwfHUbI3mqhmJDqUa27cxaRlnRZ0lzf0UtYLaAhUWe+NyQKBgQDwfABrKyf0q5Yr0yTWBldtPa1KuUYiBrKVYW8GJnS6lffEsWKqEOK5FFPdJ+bBpywCtvQY0XEwYVkl+BjRjlEn+KaGcdkslCP90Jk0FbQ98FrN2+YYsGhExUScxt5O51TH+hK+9XGLWcORdYoNWhDP3w5BhGNwOeCTjvDR9enYDwKBgQDPV7oMvc/G0LKVA+b60rTBgo4pzapX5XIpUYHqY1y93+wFjb9tU3FReoR3zsaQ2DO0vDDoOjSp7zbzocn/R6xSfEqr6XNao3U0kp/xn1dNXx4VtpBfVzDv1DZd/I4/vIcciTyUyKmboY+M5ozBkWAM9yLhT2CFKpLEdtrYEoHmyQKBgEGdA5w53R/zhPiWFlHSzx2+Gz7tCAaWnzkEqX8bFPQnoL9oyouuKb3nnu4TSfGCRA7FjhoLYv+ZP/KNG3BpjRkDzaOXAnMYRC2nMXW1ikTwBEZwffo0f25sCEliNRuAIHCjeWPiocUsi6BvWmhEL5wXttMHZP4kvHJmKKyQlOnfAoGBAKuBIACao1N5UGL78HTgrG7bDPq+DFpvmtrnJdhi+BkOdfb8ykvsiyt0/XdXzMjHPzHnhQPgDSenT/kK4f1JelJEw7wya0KF2fum3aM6HgbIqpzni1iOKWwDTfmyiPY3wWg3yFMBvOHejAHkP0XbVL4KVa0q9j+xWyeXbShuyLYj-----END PRIVATE KEY-----"
  app-auth-public-key: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6w/c9mggo9RT7KdHNjW4ownF1hVwbuhvlQRwGS12Y1u7n+9sRjYEAIIoLyWZM+8Ko/gfDSL/b6wACRJz41F7AEwQIH9xiJCiWPpX5U9As9E1TvJ38ykl1mChYcs4APPtfOb7xZZXnYrkFAkgZ2lcvm2B5bqeHWTi7qsf5djVvpKlaEFw6cIoHXwA+oKRb8rUq4UtdA3Hqe/WfZ+WozB0VcvNwfmJxea0FhJSSHAHWqhXcBP+MYoNK+3rnhjbwsxCtt0fU7xSEzzux1c26UPpeIwTNWImEuV5YI8hzsxPgVtdcsoRqedSYrtHeCC5+v6MB1q7wlw6iSvS9PelzZvmxwIDAQAB-----END PUBLIC KEY-----"
  app-receiver-endpoints: '{"program":"http://program-service.ifix:8080/ifms/program-service/v1/"}'
  service-host-url: "https://mukta-uat.digit.org/ifms/digit-exchange"
  app-exchange-topic-name: "ifix-dx-exchange-topic"
  app-error-topic-name: "ifix-dx-exchange-error-queue"
  app-events-log-topic-name: "ifix-dx-exchange-event-log-queue"

program-service:
  tracing-enabled: true
  java-enable-debug: true
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi
  egov-idgen-idname: "ifix.program.number"
  adapter-host: "http://ifms-adapter.works:8080/"
  adapter-path: "ifms-adapter/v1/"
  search-default-limit: 20
  is-program-async: true
  is-sanction-async: false
  is-allocation-async: false
  is-disburse-async: true
  exchange-path: "ifms/digit-exchange/v1/exchange/"
  exchange-service-external-url: "https://mukta-uat.digit.org/ifms/digit-exchange"
  program-kafka-topic: "ifix-ps-program-kafka-topic"
  sanction-kafka-topic: "ifix-ps-sanction-kafka-topic"
  allocation-kafka-topic: "ifix-ps-allocation-kafka-topic"
  disburse-kafka-topic: "ifix-ps-disburse-kafka-topic"
  error-queue: "ifix-ps-error-queue"
  original-disburse-expire-days: 90
  original-disburse-expire-financial-year-date: 30
  original-disburse-expire-financial-year-month: 4