{{- if and .Values.scheduling.userScheduler.enabled .Values.scheduling.userScheduler.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-scheduler
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.scheduling.userScheduler.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
{{- end }}
