repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts

values: 
  - namespace: monitoring
  - ../../environments/mukta-prod-secrets.yaml
  - ../../environments/mukta-prod.yaml



releases:

- name: loki-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/loki-stack
  version: 2.10.1
  values:
  - ./values/loki-stack.yaml

- name: kube-prometheus-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: prometheus-community/kube-prometheus-stack
  version: 56.6.2
  disableValidation: true
  values:
  - ./values/prometheus.yaml

- name: jaeger
  installed: false
  namespace: es-cluster
  chart: jaegertracing/jaeger
  version: 0.35.0
  values:
  - ./values/jaeger.yaml
  set:
    - name: query.ingress.hosts[0]
      value: "{{ .Values.domain }}"

- name: grafana
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/grafana
  version: 7.3.0
  values:
  - ./values/grafana.yaml
  - envRenderSecret:
      GF_AUTH_GITHUB_CLIENT_ID: {{ index .Values "cluster-configs" "secrets" "grafana" "clientID" }}
      GF_AUTH_GITHUB_CLIENT_SECRET: {{ index .Values "cluster-configs" "secrets" "grafana" "clientSecret" }}
  set:
    - name: ingress.hosts[0]
      value: "{{ .Values.domain }}"
    - name: ingress.tls[0].hosts[0]
      value: "{{ .Values.domain }}"

- name: blackbox
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: ../backbone-services/prometheus-blackbox-exporter
  version: 8.2.0